# Intro to Pandas

Pandas is a high-level data manipulation package/library which was built on top of NumPy. The key structures within pandas include Series and DataFrames.

In [2]:
# Importing NumPy and Pandas
import numpy as np
import pandas as pd
# from pandas import Series, DataFrame

In [4]:
# Creating a Series out of a list --> A Series is a 1 dimensional array with labels
x_series = pd.Series([10,20,30,40,50])
x_series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
# We can access different components of the Series if we want

# Index
print(x_series.index)

# Values
print(x_series.values)

# DType
print(x_series.dtype)

RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
int64

In [6]:
# Create a Series with an index
data = [450, 650, 870]
Sales = pd.Series(data, index=["Don", "Mike", "Edwin"])
Sales

Don      450
Mike     650
Edwin    870
dtype: int64

In [7]:
# check the type
print(type(Sales))

<class 'pandas.core.series.Series'>

In [8]:
# Accesssing Values

# Using index name
print(Sales["Don"])

# Using indexing
print(Sales.iloc[0])

450
450

### Checking for conditions

In [19]:
# We can filter our data based on conditions that we specify. We usually do this with booleans.

# Sales greater than 500
Sales>500

Don      False
Mike      True
Edwin     True
dtype: bool

In [20]:
# Return the values greater than 500
Sales[Sales>500]

Mike     650
Edwin    870
dtype: int64

In [9]:
# Check for index names in a Series
"Don" in Sales

True

In [10]:
# We can only check if something is in an index. See below:
450 in Sales

False

### Working with Dictionaries

In [11]:
# Converting a Series to a Dictionary
sales_dict = Sales.to_dict()
sales_dict

{'Don': 450, 'Mike': 650, 'Edwin': 870}

In [12]:
# Converting a Dictionary to a Series
Sales_ser = pd.Series(sales_dict)
Sales_ser

Don      450
Mike     650
Edwin    870
dtype: int64

### Adding entries and working with NaN/Null values

In [15]:
# We can create a new Series from an existing Series
# If we specify names in the index that were not there already, they will be assigned NaN values
# NaN = Not a Number

New_sales = pd.Series(Sales, index=["Don", "Mike", "Sally", "Edwin", "Lucy"])
New_sales

Don      450.0
Mike     650.0
Sally      NaN
Edwin    870.0
Lucy       NaN
dtype: float64

In [17]:
# Check if entries/value are NaN --> Can use NumPy for this
print(np.isnan(New_sales["Sally"]))

True

In [18]:
# This is different to None
New_sales["Sally"] is None

False

In [19]:
# We can check for NaN's on the entire Series
np.isnan(New_sales)

Don      False
Mike     False
Sally     True
Edwin    False
Lucy      True
dtype: bool

In [20]:
# Checking for null values with Pandas
pd.isnull(New_sales)

Don      False
Mike     False
Sally     True
Edwin    False
Lucy      True
dtype: bool

### Naming components in a Series

In [22]:
# Naming an index
Sales.index.name = "SalesPerson"
Sales

SalesPerson
Don      450
Mike     650
Edwin    870
dtype: int64

In [23]:
# Naming a Series
Sales.name = "Total TV Sales"
Sales

SalesPerson
Don      450
Mike     650
Edwin    870
Name: Total TV Sales, dtype: int64

## DataFrames

DataFrames are two-dimensional, size-mutable, potentially heterogenous(diverse) tabular data structures.

Essentially a data structure with labelled axes (rows and columns).

### Creating DataFrames

In [26]:
# Creating a DF from a list
data = [["Adrian", 20],["Bethany", 23],["Chloe", 41]]

# Remember to add the column names if making a DF from a list
df1 = pd.DataFrame(data, columns=["Name", "Age"])
df1

      Name  Age
0   Adrian   20
1  Bethany   23
2    Chloe   41

In [28]:
# Creating a DF from a Dictionary
new_dict = {'Name':['Tom','Jane','Steve','Lucy'],'Sales':[250,300,350,400]}

df_dict1 = pd.DataFrame(new_dict)
df_dict1

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [30]:
# Adding a custom index
df_dict_index1 = pd.DataFrame(new_dict, index=["rank4", "rank3", "rank2", "rank1"])
df_dict_index1

        Name  Sales
rank4    Tom    250
rank3   Jane    300
rank2  Steve    350
rank1   Lucy    400

In [31]:
# Creating a DF from a list of Dictionaries
# Why useful? --> Mimics JSON data
dict_list = [{'Name':'Tom','Sales':250},{'Name':'Jane','Sales':300},{'Name':'Steve','Sales':350}
            ,{'Name':'Lucy','Sales':400}]

df_dict_list = pd.DataFrame(dict_list)
df_dict_list

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [34]:
# Combining Pandas Series into a single DataFrame part 1 - Creating the Series
east = pd.Series([1000,1200,3400],index=['Q1','Q2','Q3'])
west = pd.Series([1100,1300,2400,3500],index=['Q1','Q2','Q3','Q4'])
print(east)
print(west)

Q1    1000
Q2    1200
Q3    3400
dtype: int64
Q1    1100
Q2    1300
Q3    2400
Q4    3500
dtype: int64

In [35]:
# Combining Pandas Series into a single DataFrame part 2 - Creating the DF
df_regions = pd.DataFrame({"East":east, "West":west})
df_regions

      East  West
Q1  1000.0  1100
Q2  1200.0  1300
Q3  3400.0  2400
Q4     NaN  3500

In [36]:
# Once we have a DataFrame, we can easily add Series on
df_regions["North"] = [2000,3000,2500,4000]
df_regions["South"] = [1500,2000,1500,4000]
df_regions

      East  West  North  South
Q1  1000.0  1100   2000   1500
Q2  1200.0  1300   3000   2000
Q3  3400.0  2400   2500   1500
Q4     NaN  3500   4000   4000

In [37]:
# If we made a mistake and need to set a new index, we can add a new column
# and set that new column as the index

years = ['2020','2021','2022','2023']
df_regions["Years"] = years
df_regions

      East  West  North  South Years
Q1  1000.0  1100   2000   1500  2020
Q2  1200.0  1300   3000   2000  2021
Q3  3400.0  2400   2500   1500  2022
Q4     NaN  3500   4000   4000  2023

In [38]:
# We can use set_index to set the index to a column in the DF
df_regions = df_regions.set_index("Years")
df_regions

         East  West  North  South
Years
2020   1000.0  1100   2000   1500
2021   1200.0  1300   3000   2000
2022   3400.0  2400   2500   1500
2023      NaN  3500   4000   4000

In [39]:
# Changing the index values, we can use reindex()
new_regions_df = df_regions.reindex(["2022", "2023", "2024", "2025", "2026"])
new_regions_df

         East    West   North   South
Years
2022   3400.0  2400.0  2500.0  1500.0
2023      NaN  3500.0  4000.0  4000.0
2024      NaN     NaN     NaN     NaN
2025      NaN     NaN     NaN     NaN
2026      NaN     NaN     NaN     NaN

In [40]:
# reindexing columns
reindex_df = new_regions_df.reindex(columns=["North", "East", "South", "New"])
reindex_df

        North    East   South  New
Years
2022   2500.0  3400.0  1500.0  NaN
2023   4000.0     NaN  4000.0  NaN
2024      NaN     NaN     NaN  NaN
2025      NaN     NaN     NaN  NaN
2026      NaN     NaN     NaN  NaN